version: "3"
services:
  client:
    build: ./app # Diretório da aplicação Vue.js
    ports:
      - "4173:4173" # Porta que será exposta para o client (ajuste conforme necessário)
    networks:
      - app-network

  server:
    build: ./server # Diretório do servidor Node.js
    ports:
      - "3000:3000" # Porta que será exposta para o server (ajuste conforme necessário)
    networks:
      - app-network
  mongodb:
    image: mongo
    ports:
      - "27018:27017"
    volumes:
      - mongodb_data:/data/db
volumes:
  mongodb_data:

networks:
  app-network:
